[theme]
name = "nord-dark"
[icons]
name = "awesome"

[[block]]
block = "networkmanager"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+"]
interface_name_include = []

[[block]]
block = "memory"
display_type = "memory"
format_mem = "mem/{mem_used_percents}"
format_swap = "swap/{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1
format = "cpu |{barchart}|"

[[block]]
block = "sound"
format = "{volume}"

[[block]]
block = "time"
interval = 1
format = "%m/%d/%a %T"

[[block]]
block = "battery"
driver = "upower"
format = "{percentage} {time}"
full_format = "{percentage} {time}"
